default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # 以下、3行追加
  username: root # 設定したPostgreSQL Accountと同一のもの
  password: password # 設定したPostgreSQL Accountと同一のもの
  host: localhost
development:
  <<: *default
  database: kintai_dev # appnameのところは、rails new時のappnameになっているはずです。
test:
  <<: *default
  database: kintai_test # appnameのところは、rails new時のappnameになっているはずです。
production:
  <<: *default
  database: kintai_prod # appnameのところは、rails new時のappnameになっているはずです。
